branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: air_bnb_clone_integrity
  branch: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  workspace_type: Application
