# Generated by Django 3.1.4 on 2021-01-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210103_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confiremd'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
