# Generated by Django 3.1.4 on 2021-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comunication',
            new_name='communication',
        ),
    ]
